#Goal
# Send cartesian coordinates to robot 

# Coordinates
float64 x
float64 y
float64 z
#Yaw, Pitch, and Roll. In the range of [-6.0, 6.0]
# If the default value is not changed it will maintain the current WPR
float64 w 6
float64 p 6
float64 r 6
---
#Result
bool success
---
#Feedback
float64[] distance_left